### ISSUE TITLE
Remove getter signatures

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-class#10]
I believe that get as part of `define` is not needed. The async resolver is now `async(resolve)`, so normal JS getters are all that's needed. cc @justinbmeyer @phillipskevin

**Comment by matthewp** [comment]
It might be good to keep these for putting them next to type signatures, if used.

**Comment by phillipskevin** [comment]
A type and a getter won't work together, right?

**Comment by justinbmeyer** [comment]
Yes, like can-define currently, with a 0-argument getter, a type won’t actually do anything

**Comment by matthewp** [comment]
So getter in the define{} should be removed right?

**Comment by justinbmeyer** [comment]
It should not.

**Comment by matthewp** [comment]
@justinbmeyer Please explain the use case for this getter, thanks.

**Comment by matthewp** [comment]
Closed by #29, getters remain in.
