### ISSUE TITLE
Make sure setters work

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-class#11]
Setters can be done as JS setters, so they do not need to be part of `define {}`.

**Comment by justinbmeyer** [comment]
They should probably be included when a setter is mixed with type and other prop definitions

**Comment by justinbmeyer** [comment]
What I mean by that is it's nice to group all of a property's behaviors.

Instead of:

```
class Foo extends DefineClass {
  static = {


     ... lots of properties ...


     foo: {
       type: String, 
       default: 5
     },   
     

    ... lots of properties ...

    
    
  },

 
  ... setters for other properties ...

  set foo(){ ... }
}
```

You see foo in one place like:

```
class Foo extends DefineClass {
  static = {


     ... lots of properties ...


     foo: {
       type: String, 
       default: 5,
       set(){ ... }
     },   
     

    ... lots of properties ...

    
    
  },

}
```


Also, are we going to support any of the other arguments? I think define supports async setters via a resolve: https://canjs.com/doc/can-define.types.set.html

**Comment by matthewp** [comment]
Ok that makes sense. I'll update the issue to be to make sure that works then.

----

I'm not familiar with the other signature. Is there a use case that's not covered by resolvers?

**Comment by justinbmeyer** [comment]
> I'm not familiar with the other signature. Is there a use case that's not covered by resolvers?

Almost everything is covered by resolvers, even `getter`.  However, resolvers do need to be "bound" to really work, so I bet there's some use case differences.  I've found the zero-arg-side-effect setter pretty useful.

**Comment by matthewp** [comment]
Deferring JS setters to this issue: https://github.com/canjs/can-define-class/issues/17
