### ISSUE TITLE
Test against Edge

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-class#15]
Ideally we could set up saucelabs. At the very least need to do manual testing in all browsers before a release.

**Comment by matthewp** [comment]
Just did a manual test and it works in Chrome, Firefox, Safari, and Edge.

**Comment by phillipskevin** [comment]
I can get saucelabs set up next week, but if someone else wants to do it the steps are here: https://github.com/canjs/canjs/issues/3586. I'm not positive they're still 100% accurate.
