### ISSUE TITLE
Prevent defining with a string

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-class#2]
This will not be supported at first:

```js
class Thing extends DefineClass {
  static define = {
    age: "number"
  }
}
```

We should not allow:

* Strings
* Functions
* Integers

**Comment by phillipskevin** [comment]
We do want to support constructors, right? At least for built-ins like `String`.

**Comment by matthewp** [comment]
Yeah maybe. I know we want something like:

```js
class Person extends DefineClass {
  static define = {
    name: types(String)
  }
}
```

**Comment by matthewp** [comment]
Will do this after https://github.com/canjs/can-define-class/issues/3

**Comment by matthewp** [comment]
Will it be confusing if we support:

```js
class Person extends DefineClass {
  static define = {
    name: String
  }
}
```

But not:

```js
class Thing extends DefineClass {
  static define = {
    prop: MyCustomClass
  }
}
```

? To me that is slightly confusing

**Comment by matthewp** [comment]
This is done in #50. Strings are now default values like other primitives.
