### ISSUE TITLE
Implement can.getOwnEnumerableKeys symbol

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define-class#21]
`getOwnEnumerableKeys` is used to iterate over a defined class using `{{#for(...)}}`.

**Comment by phillipskevin** [comment]
We can probably copy over https://github.com/canjs/can-define/blob/c3ea493a6a13587b679ac51077a8124c8c67280d/map/map.js#L234-L238

**Comment by matthewp** [comment]
I would do that here: https://github.com/canjs/can-define-class/blob/526eda9d4be6c6c43b4ec725b3ed90e30aeb9cf2/can-define-class.js#L160
