### ISSUE TITLE
Remove single export

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-class#46]
Currently this module exports the `DefineClass` object. Instead I think it should export `define` and `DefineClass` as exports on the `exports` object. Use like:

```js
const { DefineClass, define } = require("can-define-class");
```

Will have to see if this will work with ESM as well.

**Comment by phillipskevin** [comment]
Should we consider calling `define` something else? `define(Object)` seems to cause steal to detect the module as AMD.

**Comment by matthewp** [comment]
Good point, that would work.

**Comment by matthewp** [comment]
Have an alternative name in mind? Can't think of anything offhand.

**Comment by justinbmeyer** [comment]
Nothing else in canjs exports this way. 

I think we should have this discussion in the context of DefineArray too. Any suggestions should include DefineArray’s package, export and ESM export.

**Comment by matthewp** [comment]
This isn't a core package.

**Comment by matthewp** [comment]
It's true that we should probably decide on #25 first. If the list version is included in this package (or not) would influence how the exports are decided on.

**Comment by phillipskevin** [comment]
The only alternative name I can think of is something like `mixinDefine`.

**Comment by matthewp** [comment]
That's not bad. We could have a convention of calling all of these class mixin things as `mixinFoo`, makes it easier to find a distinct name.

**Comment by phillipskevin** [comment]
This was renamed to `mixinDefine` in https://github.com/canjs/can-define-class/pull/48. We still need to change how these are exported.

**Comment by matthewp** [comment]
Superseded by #55
